In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',100)
pd.set_option('display.max_rows',100) 

df = pd.read_json('data/train/SourceData_42.json')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1509795 entries, 0 to 1509794
Data columns (total 3 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   DEVICE_ID     1509795 non-null  int64
 1   DEVICE_BD_ID  1509795 non-null  int64
 2   data          1509795 non-null  object
dtypes: int64(2), object(1)
memory usage: 34.6+ MB

In [3]:
# Numerical columns
df.select_dtypes(include=np.number).columns.tolist()

['DEVICE_ID', 'DEVICE_BD_ID']

In [4]:
df.describe() # 1.5 m counts.

       DEVICE_ID  DEVICE_BD_ID
count  1509795.0     1509795.0
mean      1333.0           1.0
std          0.0           0.0
min       1333.0           1.0
25%       1333.0           1.0
50%       1333.0           1.0
75%       1333.0           1.0
max       1333.0           1.0

In [5]:
df

,DEVICE_ID,DEVICE_BD_ID,data
0,1333,1,"{'ITEM_NAME': '누적전력량', 'ITEM_VALUE': 79569.804..."
1,1333,1,"{'ITEM_NAME': '선간전압평균', 'ITEM_VALUE': 396.25, ..."
2,1333,1,"{'ITEM_NAME': '온도', 'ITEM_VALUE': 14.375, 'TIM..."
3,1333,1,"{'ITEM_NAME': '역률평균', 'ITEM_VALUE': 0.631358, ..."
4,1333,1,"{'ITEM_NAME': '유효전력평균', 'ITEM_VALUE': 8620.5, ..."
...,...,...,...
1509790,1333,1,"{'ITEM_NAME': 'S상전류', 'ITEM_VALUE': 0, 'TIMEST..."
1509791,1333,1,"{'ITEM_NAME': 'T상역률', 'ITEM_VALUE': 0, 'TIMEST..."
1509792,1333,1,"{'ITEM_NAME': 'S상유효전력', 'ITEM_VALUE': 0, 'TIME..."
1509793,1333,1,"{'ITEM_NAME': 'R상전류고조파', 'ITEM_VALUE': 0, 'TIM..."
1509794,1333,1,"{'ITEM_NAME': 'S상선간전압', 'ITEM_VALUE': 395.25, ..."

In [6]:
# convert json into readable data format
for (idx, val) in enumerate(df['data'].values):
    if idx == 30: break
    print(val['ITEM_NAME'], val['ITEM_VALUE'], val['TIMESTAMP'])

누적전력량 79569.8047 2020-10-22 00:00:40
선간전압평균 396.25 2020-10-22 00:00:40
온도 14.375 2020-10-22 00:00:40
역률평균 0.631358 2020-10-22 00:00:40
유효전력평균 8620.5 2020-10-22 00:00:40
상전압평균 228.916672 2020-10-22 00:00:40
전압고조파평균 7.421875 2020-10-22 00:00:40
주파수 59.882084 2020-10-22 00:00:40
전류고조파평균 119.88932 2020-10-22 00:00:40
무효전력평균 10588.5 2020-10-22 00:00:40
전류평균 19.979166 2020-10-22 00:00:40
전류고조파평균 120.963539 2020-10-22 00:01:40
전압고조파평균 7.5846350000000005 2020-10-22 00:01:40
누적전력량 79715.1 2020-10-22 00:01:40
선간전압평균 395.833344 2020-10-22 00:01:40
전류평균 20.052084 2020-10-22 00:01:40
유효전력평균 8639 2020-10-22 00:01:40
온도 15 2020-10-22 00:01:40
상전압평균 229 2020-10-22 00:01:40
역률평균 0.6379589999999999 2020-10-22 00:01:40
무효전력평균 10428 2020-10-22 00:01:40
주파수 59.891457 2020-10-22 00:01:40
선간전압평균 396 2020-10-22 00:02:40
전류평균 20.291666 2020-10-22 00:02:40
역률평균 0.641102 2020-10-22 00:02:40
전압고조파평균 7.324219 2020-10-22 00:02:40
누적전력량 79860.06 2020-10-22 00:02:40
온도 15 2020-10-22 00:02:40
무효전력평균 10365 2020-10-22 00:02:40
전류고조파평균 122.200523 2020-10-22 00:02:40

In [7]:
cur_date = None # current date
for idx, val in enumerate(df['data'].values):
    if idx == 30: break
    print(val['ITEM_NAME'], val['ITEM_VALUE'], val['TIMESTAMP'])
    if cur_date is None:
        cur_date = val['TIMESTAMP']
    if cur_date == val['TIMESTAMP']:
        continue
    elif cur_date != val['TIMESTAMP']:
        print("Detect change value of TIMESTAMP")
        break

누적전력량 79569.8047 2020-10-22 00:00:40
선간전압평균 396.25 2020-10-22 00:00:40
온도 14.375 2020-10-22 00:00:40
역률평균 0.631358 2020-10-22 00:00:40
유효전력평균 8620.5 2020-10-22 00:00:40
상전압평균 228.916672 2020-10-22 00:00:40
전압고조파평균 7.421875 2020-10-22 00:00:40
주파수 59.882084 2020-10-22 00:00:40
전류고조파평균 119.88932 2020-10-22 00:00:40
무효전력평균 10588.5 2020-10-22 00:00:40
전류평균 19.979166 2020-10-22 00:00:40
전류고조파평균 120.963539 2020-10-22 00:01:40
Detect change value of TIMESTAMP

In [8]:
# Identify unique columns using set feature
column_candidate = []
for idx, val in enumerate(df['data'].values):
    column_candidate.append(val['ITEM_NAME'])
print(len(column_candidate))
set(column_candidate)

1509795

{'R상무효전력',
 'R상선간전압',
 'R상역률',
 'R상유효전력',
 'R상전류',
 'R상전류고조파',
 'R상전압',
 'R상전압고조파',
 'S상무효전력',
 'S상선간전압',
 'S상역률',
 'S상유효전력',
 'S상전류',
 'S상전류고조파',
 'S상전압',
 'S상전압고조파',
 'T상무효전력',
 'T상선간전압',
 'T상역률',
 'T상유효전력',
 'T상전류',
 'T상전류고조파',
 'T상전압',
 'T상전압고조파',
 '누적전력량',
 '무효전력평균',
 '상전압평균',
 '선간전압평균',
 '역률평균',
 '온도',
 '유효전력평균',
 '전류고조파평균',
 '전류평균',
 '전압고조파평균',
 '주파수'}

In [9]:
df['item_name'], df['item_value'], df['timestamp'] = zip(*df['data'].apply(lambda x: [x['ITEM_NAME'], x['ITEM_VALUE'], x['TIMESTAMP']]))
target = df.pivot(index='timestamp', columns='item_name', values='item_value').reset_index()

In [10]:
target

item_name,timestamp,R상무효전력,R상선간전압,R상역률,R상유효전력,R상전류,R상전류고조파,R상전압,R상전압고조파,S상무효전력,S상선간전압,S상역률,S상유효전력,S상전류,S상전류고조파,S상전압,S상전압고조파,T상무효전력,T상선간전압,T상역률,T상유효전력,T상전류,T상전류고조파,T상전압,T상전압고조파,누적전력량,무효전력평균,상전압평균,선간전압평균,역률평균,온도,유효전력평균,전류고조파평균,전류평균,전압고조파평균,주파수
0,2020-10-22 00:00:40,3611.0,397.00,0.628906,2932.5,20.28125,116.894531,229.00,7.031250,3651.0,396.25,0.625000,2947.5,20.28125,121.386719,229.25,7.519531,3326.5,395.50,0.632813,2740.5,19.37500,121.386719,228.50,7.714844,7.956980e+04,10588.5,228.916672,396.250000,0.631358,14.375,8620.5,119.889320,19.979166,7.421875,59.882084
1,2020-10-22 00:01:40,3573.5,397.25,0.628906,2910.5,20.87500,121.386719,229.25,6.933594,3645.5,395.25,0.636719,3030.0,20.68750,122.070313,229.50,7.617188,3209.0,395.00,0.640625,2698.5,18.59375,120.507813,228.25,8.007813,7.971510e+04,10428.0,229.000000,395.833344,0.637959,15.000,8639.0,120.963539,20.052084,7.584635,59.891457
2,2020-10-22 00:02:40,3534.0,397.75,0.632813,2888.5,20.43750,122.753906,230.00,6.835938,3585.5,395.50,0.640625,2996.5,21.25000,122.851563,229.00,7.324219,3245.5,394.75,0.648438,2773.5,19.18750,120.996094,228.75,7.812500,7.986006e+04,10365.0,229.250000,396.000000,0.641102,15.000,8658.5,122.200523,20.291666,7.324219,59.872750
3,2020-10-22 00:03:40,3452.5,399.00,0.644531,2940.0,19.28125,118.847656,230.00,7.617188,3433.5,396.25,0.660156,3031.5,19.75000,118.457031,230.00,7.910156,3040.5,396.00,0.660156,2693.0,17.84375,116.308594,228.75,8.300781,8.000493e+04,9926.5,229.583328,397.083344,0.657593,15.625,8664.5,117.871094,18.958334,7.942708,59.900784
4,2020-10-22 00:04:40,3615.5,397.25,0.632813,2977.5,18.87500,118.554688,229.50,7.421875,-3647.0,395.50,0.632813,2991.0,18.65625,119.726563,229.00,7.910156,3322.0,395.00,0.625000,2661.0,16.46875,117.382813,228.50,7.910156,8.014973e+04,3290.5,229.000000,395.916656,0.934377,14.375,8629.5,118.554688,18.000000,7.747396,59.714870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43132,2020-11-22 23:55:40,0.0,397.50,0.000000,0.0,0.00000,0.000000,229.50,3.027344,0.0,395.50,0.000000,0.0,0.00000,0.000000,229.25,3.027344,0.0,394.75,0.000000,0.0,0.00000,0.000000,228.50,3.320313,2.317593e+06,0.0,229.083328,395.916656,0.000000,8.125,0.0,0.000000,0.000000,3.125000,59.872757
43133,2020-11-22 23:56:40,0.0,397.50,0.000000,0.0,0.00000,0.000000,229.50,3.125000,0.0,395.75,0.000000,0.0,0.00000,0.000000,229.25,3.125000,0.0,394.50,0.000000,0.0,0.00000,0.000000,228.50,3.222656,2.317593e+06,0.0,229.083328,395.916656,0.000000,7.500,0.0,0.000000,0.000000,3.157552,59.807450
43134,2020-11-22 23:57:40,0.0,397.25,0.000000,0.0,0.00000,0.000000,229.50,3.125000,0.0,395.75,0.000000,0.0,0.00000,0.000000,229.25,3.027344,0.0,395.00,0.000000,0.0,0.00000,0.000000,228.50,3.222656,2.317593e+06,0.0,229.083328,396.000000,0.000000,8.125,0.0,0.000000,0.000000,3.125000,59.854070
43135,2020-11-22 23:58:40,0.0,397.00,0.000000,0.0,0.00000,0.000000,229.25,3.125000,0.0,396.00,0.000000,0.0,0.00000,0.000000,229.25,3.125000,0.0,395.00,0.000000,0.0,0.00000,0.000000,228.50,3.222656,2.317593e+06,0.0,229.000000,396.000000,0.000000,8.125,0.0,0.000000,0.000000,3.157552,59.844740
43136,2020-11-22 23:59:40,0.0,397.00,0.000000,0.0,0.00000,0.000000,229.50,3.222656,0.0,395.25,0.000000,0.0,0.00000,0.000000,228.75,3.125000,0.0,394.50,0.000000,0.0,0.00000,0.000000,228.50,3.320313,2.317593e+06,0.0,228.916672,395.583344,0.000000,8.125,0.0,0.000000,0.000000,3.222656,59.872740

In [11]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [12]:
target.head(10)

item_name,timestamp,R상무효전력,R상선간전압,R상역률,R상유효전력,R상전류,R상전류고조파,R상전압,R상전압고조파,S상무효전력,S상선간전압,S상역률,S상유효전력,S상전류,S상전류고조파,S상전압,S상전압고조파,T상무효전력,T상선간전압,T상역률,T상유효전력,T상전류,T상전류고조파,T상전압,T상전압고조파,누적전력량,무효전력평균,상전압평균,선간전압평균,역률평균,온도,유효전력평균,전류고조파평균,전류평균,전압고조파평균,주파수
0,2020-10-22 00:00:40,3611.0,397.00,0.628906,2932.5,20.28125,116.894531,229.00,7.031250,3651.0,396.25,0.625000,2947.5,20.28125,121.386719,229.25,7.519531,3326.5,395.50,0.632813,2740.5,19.37500,121.386719,228.50,7.714844,79569.8047,10588.5,228.916672,396.250000,0.631358,14.375,8620.5,119.889320,19.979166,7.421875,59.882084
1,2020-10-22 00:01:40,3573.5,397.25,0.628906,2910.5,20.87500,121.386719,229.25,6.933594,3645.5,395.25,0.636719,3030.0,20.68750,122.070313,229.50,7.617188,3209.0,395.00,0.640625,2698.5,18.59375,120.507813,228.25,8.007813,79715.1000,10428.0,229.000000,395.833344,0.637959,15.000,8639.0,120.963539,20.052084,7.584635,59.891457
2,2020-10-22 00:02:40,3534.0,397.75,0.632813,2888.5,20.43750,122.753906,230.00,6.835938,3585.5,395.50,0.640625,2996.5,21.25000,122.851563,229.00,7.324219,3245.5,394.75,0.648438,2773.5,19.18750,120.996094,228.75,7.812500,79860.0600,10365.0,229.250000,396.000000,0.641102,15.000,8658.5,122.200523,20.291666,7.324219,59.872750
3,2020-10-22 00:03:40,3452.5,399.00,0.644531,2940.0,19.28125,118.847656,230.00,7.617188,3433.5,396.25,0.660156,3031.5,19.75000,118.457031,230.00,7.910156,3040.5,396.00,0.660156,2693.0,17.84375,116.308594,228.75,8.300781,80004.9300,9926.5,229.583328,397.083344,0.657593,15.625,8664.5,117.871094,18.958334,7.942708,59.900784
4,2020-10-22 00:04:40,3615.5,397.25,0.632813,2977.5,18.87500,118.554688,229.50,7.421875,-3647.0,395.50,0.632813,2991.0,18.65625,119.726563,229.00,7.910156,3322.0,395.00,0.625000,2661.0,16.46875,117.382813,228.50,7.910156,80149.7300,3290.5,229.000000,395.916656,0.934377,14.375,8629.5,118.554688,18.000000,7.747396,59.714870
5,2020-10-22 00:05:40,3557.0,397.50,0.625000,2853.0,18.09375,109.277344,229.75,7.421875,3697.0,395.50,0.632813,3048.5,18.75000,111.328125,229.25,7.421875,3326.0,394.50,0.644531,2805.5,16.18750,112.109375,228.50,8.203125,80295.1250,10580.0,229.166672,395.833344,0.635449,14.375,8707.0,110.904945,17.677084,7.682292,59.863403
6,2020-10-22 00:06:40,3411.0,396.75,0.648438,2923.5,20.56250,117.675781,229.50,7.617188,3404.0,397.00,0.656250,2987.0,20.46875,117.578125,229.25,7.812500,2984.0,396.00,0.660156,2631.0,18.84375,116.406250,229.50,8.203125,80440.0000,9799.0,229.416672,396.583344,0.657082,14.375,8541.5,117.220055,19.958334,7.877604,59.872740
7,2020-10-22 00:07:40,3668.0,397.75,0.640625,3073.0,22.62500,123.144531,230.00,7.128906,-3657.0,395.00,0.636719,3050.5,21.31250,124.121094,228.75,7.617188,3318.0,394.50,0.625000,2668.5,19.78125,124.218750,228.50,7.714844,80585.4900,3329.0,229.083328,395.750000,0.935205,14.375,8792.0,123.828125,21.239584,7.486979,59.844750
8,2020-10-22 00:08:40,3775.0,398.00,0.621094,2993.5,18.96875,123.925781,229.50,7.421875,3810.5,397.00,0.621094,3033.0,19.56250,125.292969,229.75,7.617188,3425.0,396.00,0.625000,2759.5,18.59375,124.316406,229.00,7.617188,80731.0400,11010.5,229.416672,397.000000,0.623725,13.750,8786.0,124.511719,19.041666,7.552083,59.863403
9,2020-10-22 00:09:40,3729.0,398.00,0.613281,2912.5,19.68750,122.070313,229.50,7.421875,3839.0,397.50,0.625000,3090.5,19.90625,125.097656,230.00,7.812500,3389.0,396.75,0.625000,2715.5,17.93750,124.902344,229.00,7.910156,80876.8359,10957.0,229.500000,397.416656,0.622642,15.000,8718.5,124.023438,19.177084,7.714844,59.835594

In [13]:
target.describe()

item_name,R상무효전력,R상선간전압,R상역률,R상유효전력,R상전류,R상전류고조파,R상전압,R상전압고조파,S상무효전력,S상선간전압,S상역률,S상유효전력,S상전류,S상전류고조파,S상전압,S상전압고조파,T상무효전력,T상선간전압,T상역률,T상유효전력,T상전류,T상전류고조파,T상전압,T상전압고조파,누적전력량,무효전력평균,상전압평균,선간전압평균,역률평균,온도,유효전력평균,전류고조파평균,전류평균,전압고조파평균,주파수
count,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,4.313700e+04,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000,43137.000000
mean,1845.574912,396.273834,0.452844,1882.613899,11.628859,63.314759,229.156869,5.472361,1432.274996,395.221341,0.433347,1771.784990,11.057080,65.517958,228.478893,5.394043,1727.733920,394.438064,0.446944,1686.958183,10.616719,64.902821,228.370410,5.433444,1.154602e+06,5006.387512,228.669115,395.311507,0.467476,11.790342,5341.265213,64.578427,11.100205,5.433427,59.855604
std,1442.756192,2.526377,0.341173,1411.263171,8.783149,47.644372,1.445637,2.176280,1721.237215,2.606271,0.359571,1329.732879,8.385714,49.223454,1.471961,2.271861,1305.012499,2.623980,0.334521,1264.999370,8.043943,48.767136,1.428896,2.196166,6.451666e+05,4060.234510,1.430341,2.542686,0.354853,5.691548,4000.873277,48.537129,8.390118,2.197928,0.080154
min,-3496.500000,386.000000,-0.800781,0.000000,0.000000,0.000000,223.000000,0.000000,-3885.500000,385.000000,-0.800781,0.000000,0.000000,0.000000,223.000000,0.000000,-3214.000000,384.000000,0.000000,0.000000,0.000000,0.000000,222.750000,0.000000,9.307579e+03,-9849.500000,223.250000,385.416656,0.000000,-1.875000,0.000000,0.000000,0.000000,0.000000,57.938824
25%,0.000000,394.500000,0.000000,0.000000,0.000000,0.000000,228.250000,4.199219,0.000000,393.500000,0.000000,0.000000,0.000000,0.000000,227.500000,4.003906,0.000000,392.750000,0.000000,0.000000,0.000000,0.000000,227.500000,4.101563,6.235051e+05,0.000000,227.666672,393.583344,0.000000,7.500000,0.000000,0.000000,0.000000,4.101563,59.844740
50%,2761.500000,396.250000,0.691406,2838.500000,16.937500,94.726560,229.250000,5.175781,2567.000000,395.250000,0.691406,2654.500000,15.906250,98.730470,228.500000,4.980469,2545.750000,394.500000,0.683594,2538.500000,15.312500,97.460940,228.500000,5.078125,1.062217e+06,7859.000000,228.666672,395.333344,0.694357,11.875000,8102.250000,97.005210,16.114584,5.078125,59.863403
75%,2943.000000,398.000000,0.714844,2970.500000,18.531250,99.414060,230.250000,6.640625,2798.500000,397.000000,0.707031,2803.000000,17.656250,102.636719,229.500000,6.640625,2739.500000,396.250000,0.703125,2672.000000,17.000000,101.855469,229.250000,6.640625,1.628591e+06,8419.500000,229.666672,397.083344,0.711782,16.250000,8412.000000,101.236977,17.697916,6.640625,59.882103
max,3871.500000,405.500000,0.824219,3983.500000,27.000000,174.414063,234.250000,11.621094,3839.000000,404.500000,0.812500,3961.000000,26.062500,181.542969,233.750000,11.621094,3636.500000,403.750000,0.808594,3608.500000,24.312500,190.625000,233.000000,11.523438,2.317593e+06,11120.000000,233.666672,404.000000,0.974008,25.000000,11553.000000,182.194016,25.791666,11.490886,60.013153

In [14]:
# Feature와 Target을 합치기 위해 Labeling 된 데이터도 읽어온다.
label_df = pd.read_json('data/train/Combined_LabelledData_42_역률평균.json')
# LABEL_NAME과 TIMESTAMP를 이용하여 `data` 컬럼을 읽어온다.
label_df['label'], label_df['timestamp'] = zip(*label_df['data'].apply(lambda x: [x['LABEL_NAME'], x['TIMESTAMP']]))
label_df.head(5)

,SVC_NAME,BASE_ITEM,DEVICE_ID,DEVICE_BD_ID,COMPANY_NAME,ESTABLISH_YEAR,LOCATION,COMPANY_TYPE,COMPANY_CAT,MAJOR_PRODUCT,CONTRACT_POWER,BILL_OPTION,KEPCO_INFO,facility_name,facility_type_name,facility_vendor,facility_year,facility_capacity,facility_volt,data,label,timestamp
0,SOH,역률평균,1333,1,CO-295,1981,경북 고령군,제조,열처리,선박엔진,7000,산업용(을)고압A 선택II,05-****-****,집진기_1,공조설비,경원엔지니어링,2013,86,380,"{'ITEM_NAME': '누적전력량', 'ITEM_VALUE': 79569.804...",주의,2020-10-22 00:00:40
1,SOH,역률평균,1333,1,CO-295,1981,경북 고령군,제조,열처리,선박엔진,7000,산업용(을)고압A 선택II,05-****-****,집진기_1,공조설비,경원엔지니어링,2013,86,380,"{'ITEM_NAME': '전류평균', 'ITEM_VALUE': 19.979166,...",주의,2020-10-22 00:00:40
2,SOH,역률평균,1333,1,CO-295,1981,경북 고령군,제조,열처리,선박엔진,7000,산업용(을)고압A 선택II,05-****-****,집진기_1,공조설비,경원엔지니어링,2013,86,380,"{'ITEM_NAME': '선간전압평균', 'ITEM_VALUE': 396.25, ...",주의,2020-10-22 00:00:40
3,SOH,역률평균,1333,1,CO-295,1981,경북 고령군,제조,열처리,선박엔진,7000,산업용(을)고압A 선택II,05-****-****,집진기_1,공조설비,경원엔지니어링,2013,86,380,"{'ITEM_NAME': '전압고조파평균', 'ITEM_VALUE': 7.42187...",주의,2020-10-22 00:00:40
4,SOH,역률평균,1333,1,CO-295,1981,경북 고령군,제조,열처리,선박엔진,7000,산업용(을)고압A 선택II,05-****-****,집진기_1,공조설비,경원엔지니어링,2013,86,380,"{'ITEM_NAME': '유효전력평균', 'ITEM_VALUE': 8620.5, ...",주의,2020-10-22 00:00:40

In [15]:
#Feature와 Label을 합쳐서 학습 데이터로 구성
train_data = target.merge(label_df.drop_duplicates(['timestamp', 'label'])[['timestamp', 'label']], on='timestamp', how='left')
train_data.head(10)

,timestamp,R상무효전력,R상선간전압,R상역률,R상유효전력,R상전류,R상전류고조파,R상전압,R상전압고조파,S상무효전력,S상선간전압,S상역률,S상유효전력,S상전류,S상전류고조파,S상전압,S상전압고조파,T상무효전력,T상선간전압,T상역률,T상유효전력,T상전류,T상전류고조파,T상전압,T상전압고조파,누적전력량,무효전력평균,상전압평균,선간전압평균,역률평균,온도,유효전력평균,전류고조파평균,전류평균,전압고조파평균,주파수,label
0,2020-10-22 00:00:40,3611.0,397.00,0.628906,2932.5,20.28125,116.894531,229.00,7.031250,3651.0,396.25,0.625000,2947.5,20.28125,121.386719,229.25,7.519531,3326.5,395.50,0.632813,2740.5,19.37500,121.386719,228.50,7.714844,79569.8047,10588.5,228.916672,396.250000,0.631358,14.375,8620.5,119.889320,19.979166,7.421875,59.882084,주의
1,2020-10-22 00:01:40,3573.5,397.25,0.628906,2910.5,20.87500,121.386719,229.25,6.933594,3645.5,395.25,0.636719,3030.0,20.68750,122.070313,229.50,7.617188,3209.0,395.00,0.640625,2698.5,18.59375,120.507813,228.25,8.007813,79715.1000,10428.0,229.000000,395.833344,0.637959,15.000,8639.0,120.963539,20.052084,7.584635,59.891457,주의
2,2020-10-22 00:02:40,3534.0,397.75,0.632813,2888.5,20.43750,122.753906,230.00,6.835938,3585.5,395.50,0.640625,2996.5,21.25000,122.851563,229.00,7.324219,3245.5,394.75,0.648438,2773.5,19.18750,120.996094,228.75,7.812500,79860.0600,10365.0,229.250000,396.000000,0.641102,15.000,8658.5,122.200523,20.291666,7.324219,59.872750,주의
3,2020-10-22 00:03:40,3452.5,399.00,0.644531,2940.0,19.28125,118.847656,230.00,7.617188,3433.5,396.25,0.660156,3031.5,19.75000,118.457031,230.00,7.910156,3040.5,396.00,0.660156,2693.0,17.84375,116.308594,228.75,8.300781,80004.9300,9926.5,229.583328,397.083344,0.657593,15.625,8664.5,117.871094,18.958334,7.942708,59.900784,주의
4,2020-10-22 00:04:40,3615.5,397.25,0.632813,2977.5,18.87500,118.554688,229.50,7.421875,-3647.0,395.50,0.632813,2991.0,18.65625,119.726563,229.00,7.910156,3322.0,395.00,0.625000,2661.0,16.46875,117.382813,228.50,7.910156,80149.7300,3290.5,229.000000,395.916656,0.934377,14.375,8629.5,118.554688,18.000000,7.747396,59.714870,주의
5,2020-10-22 00:05:40,3557.0,397.50,0.625000,2853.0,18.09375,109.277344,229.75,7.421875,3697.0,395.50,0.632813,3048.5,18.75000,111.328125,229.25,7.421875,3326.0,394.50,0.644531,2805.5,16.18750,112.109375,228.50,8.203125,80295.1250,10580.0,229.166672,395.833344,0.635449,14.375,8707.0,110.904945,17.677084,7.682292,59.863403,주의
6,2020-10-22 00:06:40,3411.0,396.75,0.648438,2923.5,20.56250,117.675781,229.50,7.617188,3404.0,397.00,0.656250,2987.0,20.46875,117.578125,229.25,7.812500,2984.0,396.00,0.660156,2631.0,18.84375,116.406250,229.50,8.203125,80440.0000,9799.0,229.416672,396.583344,0.657082,14.375,8541.5,117.220055,19.958334,7.877604,59.872740,주의
7,2020-10-22 00:07:40,3668.0,397.75,0.640625,3073.0,22.62500,123.144531,230.00,7.128906,-3657.0,395.00,0.636719,3050.5,21.31250,124.121094,228.75,7.617188,3318.0,394.50,0.625000,2668.5,19.78125,124.218750,228.50,7.714844,80585.4900,3329.0,229.083328,395.750000,0.935205,14.375,8792.0,123.828125,21.239584,7.486979,59.844750,주의
8,2020-10-22 00:08:40,3775.0,398.00,0.621094,2993.5,18.96875,123.925781,229.50,7.421875,3810.5,397.00,0.621094,3033.0,19.56250,125.292969,229.75,7.617188,3425.0,396.00,0.625000,2759.5,18.59375,124.316406,229.00,7.617188,80731.0400,11010.5,229.416672,397.000000,0.623725,13.750,8786.0,124.511719,19.041666,7.552083,59.863403,주의
9,2020-10-22 00:09:40,3729.0,398.00,0.613281,2912.5,19.68750,122.070313,229.50,7.421875,3839.0,397.50,0.625000,3090.5,19.90625,125.097656,230.00,7.812500,3389.0,396.75,0.625000,2715.5,17.93750,124.902344,229.00,7.910156,80876.8359,10957.0,229.500000,397.416656,0.622642,15.000,8718.5,124.023438,19.177084,7.714844,59.835594,주의

In [16]:
train_data.shape

(43137, 37)

In [17]:
train_data.dtypes

timestamp     object
R상무효전력       float64
R상선간전압       float64
R상역률         float64
R상유효전력       float64
R상전류         float64
R상전류고조파      float64
R상전압         float64
R상전압고조파      float64
S상무효전력       float64
S상선간전압       float64
S상역률         float64
S상유효전력       float64
S상전류         float64
S상전류고조파      float64
S상전압         float64
S상전압고조파      float64
T상무효전력       float64
T상선간전압       float64
T상역률         float64
T상유효전력       float64
T상전류         float64
T상전류고조파      float64
T상전압         float64
T상전압고조파      float64
누적전력량        float64
무효전력평균       float64
상전압평균        float64
선간전압평균       float64
역률평균         float64
온도           float64
유효전력평균       float64
전류고조파평균      float64
전류평균         float64
전압고조파평균      float64
주파수          float64
label         object
dtype: object

In [18]:
train_data['label'].unique()

array(['주의', '정상', '경고'], dtype=object)

In [19]:
train_data['label'].astype('category')

0        주의
1        주의
2        주의
3        주의
4        주의
         ..
43132    경고
43133    경고
43134    경고
43135    경고
43136    경고
Name: label, Length: 43137, dtype: category
Categories (3, object): ['경고', '정상', '주의']

In [20]:
train_data['label'] = train_data['label'].astype('category')
train_data['label']
# train_data.head(10)

0        주의
1        주의
2        주의
3        주의
4        주의
         ..
43132    경고
43133    경고
43134    경고
43135    경고
43136    경고
Name: label, Length: 43137, dtype: category
Categories (3, object): ['경고', '정상', '주의']

In [21]:
train_data['label'] = train_data['label'].astype('category').cat
train_data['label']

0        <pandas.core.arrays.categorical.CategoricalAcc...
1        <pandas.core.arrays.categorical.CategoricalAcc...
2        <pandas.core.arrays.categorical.CategoricalAcc...
3        <pandas.core.arrays.categorical.CategoricalAcc...
4        <pandas.core.arrays.categorical.CategoricalAcc...
                               ...
43132    <pandas.core.arrays.categorical.CategoricalAcc...
43133    <pandas.core.arrays.categorical.CategoricalAcc...
43134    <pandas.core.arrays.categorical.CategoricalAcc...
43135    <pandas.core.arrays.categorical.CategoricalAcc...
43136    <pandas.core.arrays.categorical.CategoricalAcc...
Name: label, Length: 43137, dtype: object

In [22]:
train_data['label'] = train_data['label'].astype('category').cat.codes
train_data['label']

0        0
1        0
2        0
3        0
4        0
        ..
43132    0
43133    0
43134    0
43135    0
43136    0
Name: label, Length: 43137, dtype: int8